Repository ethereumjs/ethereumjs-client, pull requests merged in 2020-06, with the labels that each got.

#113 Explicitly initialize Common instances with chainstart HF
  bin/cli.js
  lib/blockchain/chain.js
  lib/service/ethereumservice.js
Labels: PR state: needs review

#119 Upgrade CI Provider to GH Actions
  .github/workflows/build.yml
  .travis.yml
  README.md
  karma.conf.js
  package.json
Labels: PR state: needs review

#120 remove old fields `consensus` and `finality`
  lib/util/parse.js
  test/util/params.json
Labels: PR state: needs review, type: refactor

#124 Added JSON-RPC documentation to README
  README.md
Labels: PR state: needs review

#127 Fix lightsync block init bug
  README.md
  browser_sync.png
  lib/service/ethereumservice.js
  lib/service/fastethereumservice.js
  lib/service/lightethereumservice.js
  lib/sync/fastsync.js
  lib/sync/fetcher/blockfetcher.js
  lib/sync/fetcher/fetcher.js
  lib/sync/lightsync.js
  lib/sync/sync.js
Labels: PR state: needs review

#129 Upgrade ethereumjs-util to v7.0.2
  lib/rpc/modules/web3.js
  lib/util/parse.js
  package.json
Labels: PR state: merge ready, PR state: needs review

#131 Add rpc method `eth_blockNumber`
  lib/rpc/modules/eth.js
  lib/rpc/validation.js
  package.json
  test/rpc/eth/getBlockNumber.js
  test/rpc/helpers.js
Labels: PR state: needs review, type: feature

#132 Updated ethereumjs-devp2p dependency to v3.0.1
  package.json
Labels: PR state: needs review

#133 Improve sync reliability
  lib/net/peerpool.js
  lib/net/protocol/ethprotocol.js
  lib/net/protocol/lesprotocol.js
  lib/net/protocol/protocol.js
  lib/net/server/rlpxserver.js
  lib/service/ethereumservice.js
  lib/service/service.js
  lib/sync/fetcher/fetcher.js
  test/blockchain/chain.js
  test/integration/peerpool.js
  test/service/fastethereumservice.js
Labels: PR state: needs review

#135 New release v0.0.6
  CHANGELOG.md
  README.md
  package.json
Labels: PR state: needs review
