Repository ethereumjs/ethereumjs-client, pull requests merged in 2020-10, with the labels that each got.

#146 Changing Karma browser concurrency to 1
  karma.conf.js
Labels: PR state: merge ready, PR state: needs review, type: tests

#150 Fix getBlockByHash tsc error
  lib/rpc/modules/eth.ts
Labels: PR state: needs review, type: bug

#151 Upgrade @ethereumjs/config-coverage and nyc
  .nycrc
  package.json
Labels: PR state: needs review, type: CI

#152 Upgrade to @ethereumjs/config-typescript
  package.json
  test/blockchain/chain.spec.ts
  test/integration/fastethereumservice.ts
  test/integration/fastsync.ts
  test/integration/lightethereumservice.ts
  test/integration/lightsync.ts
  test/integration/node.ts
  test/integration/peerpool.ts
  test/logging.ts
  test/net/peer/libp2pnode.ts
  test/net/peer/peer.ts
  test/net/peer/rlpxpeer.ts
  test/net/peerpool.ts
  test/net/protocol/boundprotocol.ts
  test/net/protocol/ethprotocol.ts
  test/net/protocol/flowcontrol.ts
  test/net/protocol/lesprotocol.ts
  test/net/protocol/libp2psender.ts
  test/net/protocol/protocol.ts
  test/net/protocol/rlpxsender.ts
  test/net/protocol/sender.ts
  test/net/server/libp2pserver.ts
  test/net/server/rlpxserver.ts
  test/node.ts
  test/rpc/eth/getBlockByHash.ts
  test/rpc/eth/getBlockByNumber.ts
  test/rpc/eth/getBlockNumber.ts
  test/rpc/eth/getBlockTransactionCountByHash.ts
  test/rpc/eth/protocolVersion.ts
  test/rpc/helpers.ts
  test/rpc/net/listening.ts
  test/rpc/net/peerCount.ts
  test/rpc/net/version.ts
  test/rpc/rpc.ts
  test/rpc/util.ts
  test/rpc/validation.ts
  test/rpc/web3/clientVersion.ts
  test/rpc/web3/sha3.ts
  test/service/fastethereumservice.ts
  test/service/lightethereumservice.ts
  test/sync/fastsync.ts
  test/sync/fetcher/blockfetcher.ts
  test/sync/fetcher/fetcher.ts
  test/sync/fetcher/headerfetcher.ts
  test/sync/lightsync.ts
  test/sync/sync.ts
  test/util/parse.ts
  tsconfig.browser.json
  tsconfig.json
  tsconfig.prod.json
Labels: PR state: needs review, type: CI

#155 Migrate browser folder files to typescript & fix npm build
  .github/workflows/build.yml
  browser/index.js
  browser/index.ts
  browser/libp2pnode.ts
  browser/logging.js
  browser/logging.ts
  tsconfig.browser.json
  webpack.config.js
Labels: PR state: needs review, type: CI, type: refactor

#158 Integrate new @ethereumjs/block, blockchain, and common packages
  bin/cli.ts
  browser/index.ts
  karma.conf.js
  lib/blockchain/chain.ts
  lib/net/protocol/ethprotocol.ts
  lib/net/protocol/lesprotocol.ts
  lib/rpc/modules/eth.ts
  lib/service/ethereumservice.ts
  lib/service/fastethereumservice.ts
  lib/sync/fetcher/blockfetcher.ts
  lib/sync/fetcher/fetcher.ts
  lib/sync/sync.ts
  lib/util/parse.ts
  package.json
  test/blockchain/chain.spec.ts
  test/integration/mocks/mockchain.ts
  test/rpc/blockChainStub.ts
  test/rpc/eth/getBlockNumber.ts
  test/rpc/helpers.ts
  test/rpc/net/version.ts
  tsconfig.karma.json
Labels: PR state: needs review, type: refactor

#162 Upgrade MPT to 4.0
  lib/util/parse.ts
  package.json
  test/util/parse.spec.ts
Labels: PR state: needs review

#163 Switch to Codecov
  .github/workflows/build.yml
  README.md
  codecov.yml
Labels: PR state: needs review

#164 Override implicit dependency lint rule for tests
  .eslintrc.js
Labels: PR state: do-not-merge
