Repository ethereumjs/ethereumjs-client, pull requests merged in 2020-11, with the labels that each got.

#168 Update winston to v3.3.3
  package.json
Labels: PR state: do-not-merge

#161 New Config Class
  bin/cli.ts
  lib/config.ts
  lib/node.ts
  lib/service/ethereumservice.ts
  lib/service/fastethereumservice.ts
  lib/service/lightethereumservice.ts
  package.json
Labels: PR state: needs review

#174 Removing path traversal to run script
  package.json
Labels: PR state: merge ready, PR state: needs review

#139 Add admin_* RPC
  lib/net/server/rlpxserver.ts
  lib/rpc/modules/admin.ts
  lib/rpc/modules/index.ts
  lib/rpc/modules/web3.ts
  lib/util/index.ts
  test/net/server/rlpxserver.ts
  test/rpc/admin/nodeInfo.ts
  test/rpc/helpers.ts
Labels: PR state: WIP, PR state: needs review, help wanted, type: feature

#178 Type option interfaces
  bin/cli.ts
  lib/blockchain/chain.ts
  lib/config.ts
  lib/logging.ts
  lib/net/peer/libp2ppeer.ts
  lib/net/peer/peer.ts
  lib/net/peer/rlpxpeer.ts
  lib/net/peerpool.ts
  lib/net/protocol/boundprotocol.ts
  lib/net/protocol/ethprotocol.ts
  lib/net/protocol/flowcontrol.ts
  lib/net/protocol/lesprotocol.ts
  lib/net/protocol/protocol.ts
  lib/net/server/libp2pserver.ts
  lib/net/server/rlpxserver.ts
  lib/net/server/server.ts
  lib/node.ts
  lib/rpc/index.ts
  lib/rpc/modules/admin.ts
  lib/service/ethereumservice.ts
  lib/service/fastethereumservice.ts
  lib/service/lightethereumservice.ts
  lib/service/service.ts
  lib/sync/fastsync.ts
  lib/sync/fetcher/blockfetcher.ts
  lib/sync/fetcher/fetcher.ts
  lib/sync/fetcher/headerfetcher.ts
  lib/sync/sync.ts
  lib/types.ts
  lib/util/parse.ts
  package.json
  test/blockchain/chain.spec.ts
  test/config.ts
  test/integration/fastethereumservice.ts
  test/integration/fastsync.ts
  test/integration/lightethereumservice.ts
  test/integration/lightsync.ts
  test/integration/mocks/mockchain.ts
  test/integration/mocks/mockserver.ts
  test/integration/node.ts
  test/integration/peerpool.ts
  test/integration/util.ts
  test/net/peer/libp2ppeer.ts
  test/net/peer/rlpxpeer.ts
  test/net/peerpool.ts
  test/net/protocol/boundprotocol.ts
  test/net/protocol/rlpxsender.ts
  test/net/server/libp2pserver.ts
  test/net/server/rlpxserver.ts
  test/node.ts
  test/service/fastethereumservice.ts
  test/service/lightethereumservice.ts
  test/sync/fastsync.ts
  test/sync/fetcher/blockfetcher.ts
  test/sync/fetcher/fetcher.ts
  test/sync/fetcher/headerfetcher.ts
  test/sync/lightsync.ts
  test/sync/sync.ts
  test/util/parse.spec.ts
Labels: PR state: needs review

#184 Rename fast sync to full sync
  README.md
  bin/cli.ts
  browser/index.ts
  lib/blockchain/chain.ts
  lib/config.ts
  lib/index.ts
  lib/node.ts
  lib/service/fullethereumservice.ts
  lib/service/index.ts
  lib/sync/fullsync.ts
  lib/sync/index.ts
  test/integration/fullethereumservice.spec.ts
  test/integration/fullsync.spec.ts
  test/integration/lightsync.spec.ts
  test/integration/node.spec.ts
  test/integration/util.ts
  test/service/fullethereumservice.spec.ts
  test/sync/fullsync.spec.ts
Labels: PR state: needs review

#182 Fix remaining skipped tests
  lib/blockchain/chain.ts
  lib/config.ts
  lib/logging.ts
  lib/net/peer/libp2pnode.ts
  lib/net/peer/rlpxpeer.ts
  lib/net/peerpool.ts
  lib/net/protocol/lesprotocol.ts
  lib/net/server/libp2pserver.ts
  lib/net/server/rlpxserver.ts
  lib/sync/fetcher/fetcher.ts
  lib/sync/lightsync.ts
  lib/sync/sync.ts
  package.json
  test/integration/fullethereumservice.spec.ts
  test/integration/lightsync.spec.ts
  test/integration/node.spec.ts
  test/integration/peerpool.spec.ts
  test/integration/util.ts
  test/net/peer/libp2pnode.spec.ts
  test/net/peer/libp2ppeer.spec.ts
  test/net/peer/peer.spec.ts
  test/net/peer/rlpxpeer.spec.ts
  test/net/peerpool.spec.ts
  test/net/protocol/boundprotocol.spec.ts
  test/net/protocol/ethprotocol.spec.ts
  test/net/protocol/flowcontrol.spec.ts
  test/net/protocol/lesprotocol.spec.ts
  test/net/protocol/protocol.spec.ts
  test/net/protocol/rlpxsender.spec.ts
  test/net/protocol/testdouble-timers.d.ts
  test/net/server/libp2pserver.spec.ts
  test/net/server/rlpxserver.spec.ts
  test/node.spec.ts
  test/service/fullethereumservice.spec.ts
  test/service/lightethereumservice.spec.ts
  test/sync/fetcher/blockfetcher.spec.ts
  test/sync/fetcher/fetcher.spec.ts
  test/sync/fetcher/headerfetcher.spec.ts
  test/sync/fullsync.spec.ts
  test/sync/lightsync.spec.ts
  test/sync/sync.spec.ts
  typedoc.json
Labels: PR state: merge ready, PR state: needs review, type: tests

#187 Integrate VM
  bin/cli.ts
  lib/service/fullethereumservice.ts
  package.json
Labels: PR state: needs review

#188 Early-stage Programmatic API / Custom VM Option
  README.md
  bin/cli.ts
  browser/index.ts
  lib/client.ts
  lib/config.ts
  lib/index.ts
  lib/index_old.ts
  lib/logging.ts
  lib/rpc/index.ts
  lib/rpc/modules/admin.ts
  lib/service/fullethereumservice.ts
  lib/sync/fullsync.ts
  package.json
  test/client.spec.ts
  test/integration/client.spec.ts
  test/sync/fullsync.spec.ts
  webpack.config.js
Labels: PR state: needs review, type: enhancement
